version: "3.8"

services:
  palworld:
    build: .
    image: palworld-wine-server:local
    container_name: palworld-wine-server
    restart: unless-stopped
    network_mode: host
    stop_grace_period: 30s
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - ./default.env
    volumes:
      - ./game:/palworld
